flCallbacks.c File Reference
#include `flGlobal.h`
#include <pspkernel.h>
#include <psppower.h>
#include <pspdisplay.h>
Functions
int callbackExit (int inArg1, int inArg2, void *inCommon)
This is called when funclib is quit via the HOME menu on the PSP, it simply calls flTerminate() and returns.
int callbackCreateThread (SceSize args, void *argp)
This is called by callbackInit(), and is executed in the callbacks thread.
int callbackInit ()
This is called by flInitialize() to initialize callbacks.
Function Documentation
int callbackCreateThread (SceSize args, void * argp)
This is called by callbackInit(), and is executed in the callbacks thread.
Returns: Always 0.
See also: callbackInit()
Warning: This shouldn't be be called except internally by funcLib itself.
Definition at line 53 of file flCallbacks.c.
References callbackExit(), debugError, and NULL.
Referenced by callbackInit().
int callbackExit (int inArg1, int inArg2, void * inCommon)
This is called when funclib is quit via the HOME menu on the PSP, it simply calls flTerminate() and returns.
Parameters:
inArg1 Unused
inArg2 Unused
inCommon Unused
Returns: Always 0.
See also: flTerminate()
Warning: This shouldn't be be called except internally by funcLib itself.
Definition at line 18 of file flCallbacks.c.
References flTerminate().
Referenced by callbackCreateThread().
int callbackInit ()
This is called by flInitialize() to initialize callbacks.
Returns: The thread ID of the callback thread.
See also: flInitialize()
Warning: This shouldn't be be called except internally by funcLib itself.
Definition at line 86 of file flCallbacks.c.
References callbackCreateThread().
Referenced by flInitialize().