flFile.h File Reference
#include `flGlobal.h`
Classes
struct FileDirEntry
struct File
Defines
#define FILE_MODE_APPEND (0)
#define FILE_MODE_READ (1)
#define FILE_MODE_WRITE (2)
#define FILE_MODE_BINARY (4)
#define FILE_MODE_READWRITE (8)
#define FILE_TYPE_FILE (0)
#define FILE_TYPE_MEMORY (1)
#define FILE_TYPE_ZIP (2)
#define FILE_TYPE_PBP (3)
#define FILE_STATE_NORMAL (0)
#define FILE_STATE_EOF (1)
#define FILE_STATE_ERROR (2)
#define FILE_SEEK_SET (SEEK_SET)
#define FILE_SEEK_CUR (SEEK_CUR)
#define FILE_SEEK_END (SEEK_END)
#define FILE_COPY_BLOCKSIZE 16384
Functions
File * fileOpen (char *inPath, u8 inMode)
void fileClose (File *inFile)
bool fileCheckState (File *inFile)
void fileSeek (File *inFile, long inSeek, int inMode)
int fileRead (void *inDest, int inSize, File *inFile)
int fileWrite (void *inSrc, int inSize, File *inFile)
int filePuts (char *inString, File *inFile)
char * fileGets (char *inString, int inCount, File *inFile)
bool fileEOF (File *inFile)
bool fileError (File *inFile)
char fileTypeGet (char *inPath)
bool fileExists (char *inPath)
char * fileNameFromPath (char *inPath)
char * fileExtension (char *inPath)
char * filePathValidate (char *inPath)
bool fileMkdir (char *inDir)
bool fileDelete (char *inPath)
bool fileCopy (char *inSrc, char *inDest)
Define Documentation
#define FILE_COPY_BLOCKSIZE 16384
Definition at line 40 of file flFile.h.
Referenced by fileCopy().
#define FILE_MODE_APPEND (0)
Definition at line 21 of file flFile.h.
Referenced by debugLog(), and debugLogFrom().
#define FILE_MODE_BINARY (4)
Definition at line 24 of file flFile.h.
Referenced by debugScreenshot(), mdl3dAnimLoadMD2(), texLoadBMP(), texLoadPCX(), texLoadTGA(), and texSaveTGA().
#define FILE_MODE_READ (1)
Definition at line 22 of file flFile.h.
Referenced by debugScreenshot(), mdl3dAnimLoadMD2(), mdl3dStatLoadOBJ(), texLoadBMP(), texLoadPCX(), and texLoadTGA().
#define FILE_MODE_READWRITE (8)
Definition at line 25 of file flFile.h.
#define FILE_MODE_WRITE (2)
Definition at line 23 of file flFile.h.
Referenced by mdl3dStatSaveOBJ(), and texSaveTGA().
#define FILE_SEEK_CUR (SEEK_CUR)
Definition at line 37 of file flFile.h.
Referenced by fileSeek(), and texLoadTGA().
#define FILE_SEEK_END (SEEK_END)
Definition at line 38 of file flFile.h.
Referenced by fileSeek().
#define FILE_SEEK_SET (SEEK_SET)
Definition at line 36 of file flFile.h.
Referenced by fileSeek(), mdl3dAnimLoadMD2(), and mdl3dStatLoadOBJ().
#define FILE_STATE_EOF (1)
Definition at line 33 of file flFile.h.
Referenced by fileCheckState(), and fileEOF().
#define FILE_STATE_ERROR (2)
Definition at line 34 of file flFile.h.
Referenced by fileCheckState(), and fileError().
#define FILE_STATE_NORMAL (0)
Definition at line 32 of file flFile.h.
Referenced by fileCheckState(), and fileOpen().
#define FILE_TYPE_FILE (0)
Definition at line 27 of file flFile.h.
Referenced by fileCheckState(), fileClose(), fileOpen(), fileRead(), fileSeek(), and fileWrite().
#define FILE_TYPE_MEMORY (1)
Definition at line 28 of file flFile.h.
Referenced by fileCheckState(), fileOpen(), fileRead(), fileSeek(), and fileWrite().
#define FILE_TYPE_PBP (3)
Definition at line 30 of file flFile.h.
#define FILE_TYPE_ZIP (2)
Definition at line 29 of file flFile.h.
Function Documentation
bool fileCheckState (File * inFile)
Definition at line 123 of file flFile.c.
References debugWarning, FILE_STATE_EOF, FILE_STATE_ERROR, FILE_STATE_NORMAL, FILE_TYPE_FILE, FILE_TYPE_MEMORY, File::fileData, File::filePointer, File::fileSize, File::fileState, and File::fileType.
Referenced by fileEOF(), fileError(), fileRead(), and fileWrite().
void fileClose (File * inFile)
Definition at line 109 of file flFile.c.
References debugWarning, FILE_TYPE_FILE, File::fileData, File::filePath, File::fileType, and memFree.
Referenced by debugLog(), debugLogFrom(), debugScreenshot(), mdl3dAnimLoadMD2(), mdl3dStatLoadOBJ(), texLoadBMP(), texLoadPCX(), and texLoadTGA().
bool fileCopy (char * inSrc, char * inDest)
Definition at line 415 of file flFile.c.
References debugWarning, FILE_COPY_BLOCKSIZE, and memQalloc.
bool fileDelete (char * inPath)
Definition at line 383 of file flFile.c.
References ASCII_0, ASCII_9, debugWarning, fileTypeGet(), and memFree.
Referenced by debugInit(), and memTerm().
bool fileEOF (File * inFile)
Definition at line 240 of file flFile.c.
References FILE_STATE_EOF, fileCheckState(), and File::fileState.
bool fileError (File * inFile)
Definition at line 245 of file flFile.c.
References FILE_STATE_ERROR, fileCheckState(), and File::fileState.
bool fileExists (char * inPath)
Definition at line 284 of file flFile.c.
References debugWarning.
Referenced by fileOpen(), fileTypeGet(), and mdl3dStatLoadOBJ().
char* fileExtension (char * inPath)
Definition at line 328 of file flFile.c.
References debugWarning, memAlloc, and NULL.
Referenced by mdl3dAnimLoad(), mdl3dStatLoad(), mdl3dStatSave(), texLoad(), and texSave().
char* fileGets (char * inString, int inCount, File * inFile)
Definition at line 224 of file flFile.c.
References fileRead(), and NULL.
Referenced by mdl3dStatLoadOBJ().
bool fileMkdir (char * inDir)
Definition at line 372 of file flFile.c.
References debugWarning.
char* fileNameFromPath (char * inPath)
Definition at line 303 of file flFile.c.
References debugWarning, memAlloc, memCopy, and NULL.
File* fileOpen (char * inPath, u8 inMode)
Definition at line 16 of file flFile.c.
References ASCII_0, ASCII_9, debugWarning, FILE_STATE_NORMAL, FILE_TYPE_FILE, FILE_TYPE_MEMORY, File::fileData, fileExists(), File::fileMode, File::filePath, File::filePointer, File::fileSize, File::fileState, File::fileType, memAlloc, memClear, memFree, and NULL.
Referenced by debugLog(), debugLogFrom(), debugScreenshot(), mdl3dAnimLoadMD2(), mdl3dStatLoadOBJ(), mdl3dStatSaveOBJ(), texLoadBMP(), texLoadPCX(), texLoadTGA(), and texSaveTGA().
char* filePathValidate (char * inPath)
Definition at line 361 of file flFile.c.
References NULL.
Referenced by texLoad(), and texSave().
int filePuts (char * inString, File * inFile)
Definition at line 214 of file flFile.c.
References debugWarning, and fileWrite().
Referenced by debugLog(), debugLogFrom(), and mdl3dStatSaveOBJ().
int fileRead (void * inDest, int inSize, File * inFile)
Definition at line 174 of file flFile.c.
References debugError, FILE_TYPE_FILE, FILE_TYPE_MEMORY, fileCheckState(), File::fileData, File::filePointer, File::fileSize, File::fileType, and memCopy.
Referenced by fileGets(), mdl3dAnimLoadMD2(), texLoadBMP(), texLoadPCX(), and texLoadTGA().
void fileSeek (File * inFile, long inSeek, int inMode)
Definition at line 154 of file flFile.c.
References debugWarning, FILE_SEEK_CUR, FILE_SEEK_END, FILE_SEEK_SET, FILE_TYPE_FILE, FILE_TYPE_MEMORY, File::fileData, File::filePointer, File::fileSize, and File::fileType.
Referenced by mdl3dAnimLoadMD2(), mdl3dStatLoadOBJ(), and texLoadTGA().
char fileTypeGet (char * inPath)
Definition at line 250 of file flFile.c.
References debugWarning, and fileExists().
Referenced by fileDelete().
int fileWrite (void * inSrc, int inSize, File * inFile)
Definition at line 193 of file flFile.c.
References debugError, FILE_TYPE_FILE, FILE_TYPE_MEMORY, fileCheckState(), File::fileData, File::filePointer, File::fileSize, File::fileType, and memCopy.
Referenced by filePuts(), and texSaveTGA().