flGraphics3d.c File Reference
#include `flGlobal.h`
#include <pspgu.h>
#include <pspgum.h>
Functions
void graphics3dDrawOrigin ()
void graphics3dDrawCubeWireframe ()
void graphics3dDrawCube ()
void graphics3dDrawSphere (u32 inDetail)
void graphics3dDrawCubeWireframea (vect3f inLocation, vect3f inDimensions, vect3f inRotation, u32 inColor)
void graphics3dDrawCubeColoreda (vect3f inLocation, vect3f inDimensions, vect3f inRotation, u32 inColor)
void graphics3dDrawCubeTextured (Texture *inTex)
void graphics3dDrawSphereTextured (u32 inDetail, u8 inMapType, Texture *inTex)
Function Documentation
void graphics3dDrawCube ()
Definition at line 85 of file flGraphics3d.c.
References graphics3dDrawCubeWireframe(), graphicsWireframe, vertVf::vertX, vertVf::vertY, and vertVf::vertZ.
Referenced by graphics3dDrawCubeColoreda().
void graphics3dDrawCubeColoreda (vect3f inLocation, vect3f inDimensions, vect3f inRotation, u32 inColor)
Definition at line 248 of file flGraphics3d.c.
References graphics3dDrawCube(), graphics3dDrawCubeWireframea(), and graphicsWireframe.
void graphics3dDrawCubeTextured (Texture * inTex)
Definition at line 263 of file flGraphics3d.c.
References texBind(), Texture::texMipMaps, vertTfVf::vertU, vertTfVf::vertV, vertTfVf::vertX, vertTfVf::vertY, and vertTfVf::vertZ.
void graphics3dDrawCubeWireframe ()
Definition at line 46 of file flGraphics3d.c.
References vertVf::vertX, vertVf::vertY, and vertVf::vertZ.
Referenced by graphics3dDrawCube(), and graphics3dDrawCubeWireframea().
void graphics3dDrawCubeWireframea (vect3f inLocation, vect3f inDimensions, vect3f inRotation, u32 inColor)
Definition at line 238 of file flGraphics3d.c.
References graphics3dDrawCubeWireframe().
Referenced by graphics3dDrawCubeColoreda().
void graphics3dDrawOrigin ()
Definition at line 24 of file flGraphics3d.c.
References vertcVf::vertColor, vertcVf::vertX, vertcVf::vertY, and vertcVf::vertZ.
void graphics3dDrawSphere (u32 inDetail)
Definition at line 128 of file flGraphics3d.c.
References MATH_PI, mathCosf(), mathSinf(), vertVf::vertX, vertVf::vertY, and vertVf::vertZ.
void graphics3dDrawSphereTextured (u32 inDetail, u8 inMapType, Texture * inTex)
Definition at line 328 of file flGraphics3d.c.
References MATH_PI, mathCosf(), mathSinf(), SPHERE_MAP_CYLINDER_EQUAL, texBind(), Texture::texMipMaps, vertTfVf::vertU, vertTfVf::vertV, vertTfVf::vertX, vertTfVf::vertY, and vertTfVf::vertZ.