flTimer.c File Reference
#include `flGlobal.h`
#include <stdio.h>
#include <psprtc.h>
#include <pspkernel.h>
Functions
Timer * timerCreate ()
double timerGetDeltaTime (Timer *inTimer)
void timerFree (Timer *inTimer)
void timerPauseAll ()
Variables
u64 timerPauseUntil = 0
Function Documentation
Timer* timerCreate ()
Definition at line 18 of file flTimer.c.
References debugError, memAlloc, NULL, Timer::timerTickResolution, Timer::timerTimeLast, and Timer::timerTimeNow.
Referenced by graphicsInit(), inputInit(), and ntfyInit().
void timerFree (Timer * inTimer)
Definition at line 48 of file flTimer.c.
References memFree.
double timerGetDeltaTime (Timer * inTimer)
Definition at line 32 of file flTimer.c.
References debugWarning, timerPauseUntil, Timer::timerTickResolution, Timer::timerTimeLast, and Timer::timerTimeNow.
Referenced by graphicsSwapBuffers(), inputLock(), inputPoll(), ntfyTick(), and ntfyTrayTick().
void timerPauseAll ()
Definition at line 57 of file flTimer.c.
References timerPauseUntil.
Variable Documentation
u64 timerPauseUntil = 0
Definition at line 16 of file flTimer.c.
Referenced by timerGetDeltaTime(), and timerPauseAll().