flTimer.h File Reference
#include `flGlobal.h`
Classes
struct Timer
Defines
#define timerWait(inTime) sceKernelDelayThread(inTime * 1000000)
Functions
Timer * timerCreate ()
double timerGetDeltaTime (Timer *inTimer)
void timerFree (Timer *inTimer)
void timerPauseAll ()
Define Documentation
#define timerWait(inTime) sceKernelDelayThread(inTime * 1000000)
Definition at line 38 of file flTimer.h.
Function Documentation
Timer* timerCreate ()
Definition at line 18 of file flTimer.c.
References debugError, memAlloc, NULL, Timer::timerTickResolution, Timer::timerTimeLast, and Timer::timerTimeNow.
Referenced by graphicsInit(), inputInit(), and ntfyInit().
void timerFree (Timer * inTimer)
Definition at line 48 of file flTimer.c.
References memFree.
double timerGetDeltaTime (Timer * inTimer)
Definition at line 32 of file flTimer.c.
References debugWarning, timerPauseUntil, Timer::timerTickResolution, Timer::timerTimeLast, and Timer::timerTimeNow.
Referenced by graphicsSwapBuffers(), inputLock(), inputPoll(), ntfyTick(), and ntfyTrayTick().
void timerPauseAll ()
Definition at line 57 of file flTimer.c.
References timerPauseUntil.