funcLib.h File Reference
#include <pspkernel.h>
#include `flGlobal.h`
#include `flIncludeH.h`
Functions
void flInitialize ()
Initialize funclib and all of its modules.
void flTerminate ()
Terminate funclib and all of its modules.
Variables
bool flRunning
A boolean to represent the running state of funclib, a non-zero value indicates that funclib is running.
Function Documentation
void flInitialize ()
Initialize funclib and all of its modules.
Note: This sets flRunning to a non-zero value.
Definition at line 21 of file funcLib.c.
References callbackInit(), debugInit(), debugStatusLog, flRunning, fontInit(), graphicsInit(), graphicsSetProjection(), inputInit(), mathInit(), mdlInit(), memInit(), ntfyInit(), and texInit().
void flTerminate ()
Terminate funclib and all of its modules.
Note: This sets flRunning to zero.
Definition at line 103 of file funcLib.c.
References debugStatusLog, flRunning, and memTerm().
Referenced by callbackExit(), debugCriticalErrorFrom(), and debugErrorFrom().
Variable Documentation
bool flRunning
A boolean to represent the running state of funclib, a non-zero value indicates that funclib is running.
Note: This should be used in infinite loops (e.g while(1) -> while(flRunning))
Definition at line 19 of file funcLib.c.
Referenced by flInitialize(), flTerminate(), memtDelFrom(), texTreeAdd(), texTreeFindTexByPath(), vmemStrideAlign(), vmemStrideFree(), vmemStrideFreeSpace(), and vmemStrideUsage().