// This validates the current configuration

#if FL_INCLUDE_ALL_C != 0
     #undef FL_INCLUDE_ALL_H
     #define FL_INCLUDE_ALL_H 1
#endif

#if FL_PREFIX_BOTH != 0
     #undef FL_PREFIX
     #define FL_PREFIX 0
#endif

#if FL_VSHMODE != 0
     #undef FL_CALLBACKS
     #undef FL_MEMORY_VMEM
     #undef FL_MEMORY_SCRATCHPAD
     #undef FL_MATH_VFPU
     #define FL_CALLBACKS 0
     #define FL_MEMORY_VMEM 0
     #define FL_MEMORY_SCRATCHPAD 0
     #define FL_MATH_VFPU 0
#endif

#if FL_KERNELMODE == 0
     #undef FL_NOTIFY_VOLUME
     #define FL_NOTIFY_VOLUME 0
#endif

#if FL_CALLBACKS == 0
     #undef FL_CALLBACKS_EXIT
     #undef FL_CALLBACKS_POWER
     #define FL_CALLBACKS_EXIT 0
     #define FL_CALLBACKS_POWER 0
#endif

#if FL_DEBUG == 0
     #undef FL_DEBUG_TIMESTAMP
     #undef FL_DEBUG_CALLEDFROM
     #undef FL_DEBUG_LOGGING
     #undef FL_DEBUG_ERROR
     #undef FL_DEBUG_WARNING
     #undef FL_DEBUG_DEVWARNING
     #undef FL_DEBUG_CRITICALERROR_SHOW
     #undef FL_DEBUG_CRITICALERROR_SCREENSHOT
     #define FL_DEBUG_TIMESTAMP 0
     #define FL_DEBUG_CALLEDFROM 0
     #define FL_DEBUG_LOGGING 0
     #define FL_DEBUG_ERROR 0
     #define FL_DEBUG_WARNING 0
     #define FL_DEBUG_DEVWARNING 0
     #define FL_DEBUG_CRITICALERROR_SHOW 0
     #define FL_DEBUG_CRITICALERROR_SCREENSHOT 0
#endif

#if FL_DEBUG_LOGGING == 0
     #undef FL_DEBUG_LOGCLEAR
     #undef FL_DEBUG_STATUS
     #define FL_DEBUG_LOGCLEAR 0
     #define FL_DEBUG_STATUS 0
#endif

#if FL_DEBUG_STATUS == 0
     #undef FL_DEBUG_STATUS_NOTIFY
     #define FL_DEBUG_STATUS_NOTIFY 0
#endif

#if FL_DEBUG_ERROR == 0
     #undef FL_DEBUG_ERROR_SHOW
     #undef FL_DEBUG_ERROR_NOTIFY
     #undef FL_DEBUG_ERROR_SCREENSHOT
     #define FL_DEBUG_ERROR_SHOW 0
     #define FL_DEBUG_ERROR_NOTIFY 0
     #define FL_DEBUG_ERROR_SCREENSHOT 0
#endif

#if FL_DEBUG_WARNING == 0
     #undef FL_DEBUG_WARNING_SHOW
     #undef FL_DEBUG_WARNING_NOTIFY
     #undef FL_DEBUG_WARNING_SCREENSHOT
     #define FL_DEBUG_WARNING_SHOW 0
     #define FL_DEBUG_WARNING_NOTIFY 0
     #define FL_DEBUG_WARNING_SCREENSHOT 0
#endif

#if FL_DEBUG_DEVWARNING == 0
     #undef FL_DEBUG_DEVWARNING_SHOW
     #undef FL_DEBUG_DEVWARNING_NOTIFY
     #undef FL_DEBUG_DEVWARNING_SCREENSHOT
     #define FL_DEBUG_DEVWARNING_SHOW 0
     #define FL_DEBUG_DEVWARNING_NOTIFY 0
     #define FL_DEBUG_DEVWARNING_SCREENSHOT 0
#endif

#if FL_TIMER == 0
     #undef FL_NOTIFY
     #define FL_NOTIFY 0
#endif

#if FL_MEMORY == 0
     #undef FL_MEMORY_SCRATCHPAD
     #undef FL_MEMORY_VMEM
     #undef FL_MEMORY_POOL
     #undef FL_MEMORY_PAGE
     #undef FL_MEMORY_LOGGING
     #undef FL_MEMORY_ERRORBYTES
     #define FL_MEMORY_VMEM 0
     #define FL_MEMORY_POOL 0
     #define FL_MEMORY_PAGE 0
     #define FL_MEMORY_LOGGING 0
     #define FL_MEMORY_ERRORBYTES 0
     #define FL_MEMORY_SCRATCHPAD 0
#endif

#if ((FL_MEMORY_ALIGNMENT_DEFAULT < 16) || (FL_MEMORY_ALIGNMENT_DEFAULT & 15))
     #undef FL_MEMORY_ALIGNMENT_DEFAULT
     #define FL_MEMORY_ALIGNMENT_DEFAULT 16
#endif

#if FL_MEMORY_VMEM == 0
     #undef FL_MEMORY_VMEM_OVERFLOW
     #undef FL_MEMORY_VMEM_STRIDE_FILL
     #undef FL_MEMORY_VMEM_CACHE
     #define FL_MEMORY_VMEM_OVERFLOW 0
     #define FL_MEMORY_VMEM_STRIDE_FILL 0
     #define FL_MEMORY_VMEM_CACHE 0
#endif

#if !FL_FILE
     #undef FL_FILE_PBPPLUS
     #define FL_FILE_PBPPLUS 0
#endif

#if FL_MATH == 0
     #undef FL_MATH_VFPU
     #undef FL_MATH_RANDOMSEED
     #undef FL_MATH_TRIGCACHE
     #define FL_MATH_VFPU 0
     #define FL_MATH_RANDOMSEED 0
     #define FL_MATH_TRIGCACHE 0
#endif

#if FL_MATH_TRIGCACHE < 0
     #undef FL_MATH_TRIGCACHE
     #define FL_MATH_TRIGCACHE 0
#endif

#if (FL_MATH_VFPU == 0) && (FL_MATH_RANDTYPE == FL_MATH_RAND_VFPU)
     #undef FL_MATH_RANDTYPE
     #define FL_MATH_RANDTYPE FL_MATH_RAND_STDIO
#endif

#if FL_MATH_RANDTYPE != FL_MATH_RAND_STDIO
     #undef FL_MATH_RANDOMSEED
     #define FL_MATH_RANDOMSEED 0
#endif

#if FL_GRAPHICS == 0
     #undef FL_GRAPHICS_BUFFER_COPY
     #undef FL_GRAPHICS_VSYNC_DEFAULT
     #undef FL_GRAPHICS_VSYNC_AUTO
     #undef FL_GRAPHICS_DISPLAYLIST_STATIC
     #undef FL_GRAPHICS_LINES_ANTIALIAS_DEFAULT
     #undef FL_GRAPHICS_FPS_SHOW_DEFAULT
     #undef FL_GRAPHICS_FPS_DAMP
     #undef FL_GRAPHICS_2D
     #undef FL_GRAPHICS_3D
     #undef FL_GRAPHICS_EFFECTS_FULLSCREEN
     #undef FL_DEBUG_ERROR_SCREENSHOT
     #undef FL_DEBUG_WARNING_SCREENSHOT
     #undef FL_DEBUG_DEVWARNING_SCREENSHOT
     #undef FL_DEBUG_CRITICALERROR_SCREENSHOT
     #undef FL_CAMERA
     #undef FL_TEXTURE_AUTOSWIZZLE
     #undef FL_MODEL
     #define FL_GRAPHICS_BUFFER_COPY 0
     #define FL_GRAPHICS_VSYNC_DEFAULT 0
     #define FL_GRAPHICS_VSYNC_AUTO 0
     #define FL_GRAPHICS_DISPLAYLIST_STATIC 0
     #define FL_GRAPHICS_LINES_ANTIALIAS_DEFAULT 0
     #define FL_GRAPHICS_FPS_SHOW_DEFAULT 0
     #define FL_GRAPHICS_FPS_DAMP 0
     #define FL_GRAPHICS_2D 0
     #define FL_GRAPHICS_3D 0
     #define FL_GRAPHICS_EFFECTS_FULLSCREEN 0
     #define FL_DEBUG_ERROR_SCREENSHOT 0
     #define FL_DEBUG_WARNING_SCREENSHOT 0
     #define FL_DEBUG_DEVWARNING_SCREENSHOT 0
     #define FL_DEBUG_CRITICALERROR_SCREENSHOT 0
     #define FL_CAMERA 0
     #define FL_TEXTURE_AUTOSWIZZLE 0
     #define FL_MODEL 0
#endif

#if !FL_GRAPHICS_DISP_BUFFER_VRAM
     #undef FL_GRAPHICS_COPY_BUFFER
     #define FL_GRAPHICS_COPY_BUFFER 1
#endif

#if ((FL_GRAPHICS_DISP_BUFFER_FORMAT < 0) || (FL_GRAPHICS_DISP_BUFFER_FORMAT > GU_PSM_8888))
     #undef FL_GRAPHICS_DISP_BUFFER_FORMAT
     #define FL_GRAPHICS_DISP_BUFFER_FORMAT GU_PSM_8888
#endif

#if ((FL_GRAPHICS_DRAW_BUFFER_FORMAT < 0) || (FL_GRAPHICS_DRAW_BUFFER_FORMAT > GU_PSM_8888))
     #undef FL_GRAPHICS_DRAW_BUFFER_FORMAT
     #define FL_GRAPHICS_DRAW_BUFFER_FORMAT GU_PSM_8888
#endif

#if FL_GRAPHICS_RENDERTARGET_STACK_SIZE < 2
     #undef FL_GRAPHICS_RENDERTARGET_STACK_SIZE
     #define FL_GRAPHICS_RENDERTARGET_STACK_SIZE 2
#endif

#if FL_GRAPHICS_2D == 0
     #undef FL_GRAPHICS_2D_USEDMA
     #undef FL_NOTIFY
     #define FL_GRAPHICS_2D_USEDMA 0
     #define FL_NOTIFY 0
#endif

#if FL_GRAPHICS_2D_ELLIPSE_MINLINES < 3
     #undef FL_GRAPHICS_2D_ELLIPSE_MINLINES
     #define FL_GRAPHICS_2D_ELLIPSE_MINLINES 3
#endif

#if FL_TEXTURE == 0
     #undef FL_TEXTURE_UNCACHED
     #undef FL_TEXTURE_AUTOMIPMAP
     #undef FL_TEXTURE_AUTOSWIZZLE
     #undef FL_TEXTURE_ERRORTEX
     #undef FL_TEXTURE_PRESERVENONALPHA
     #undef FL_TEXTURE_PCX
     #undef FL_TEXTURE_TGA
     #undef FL_TEXTURE_BMP
     #undef FL_TEXTURE_WAL
     #undef FL_TEXTURE_PNG
     #undef FL_TEXTURE_RAW
     #undef FL_TEXTURE_MANIPULATION
     #undef FL_SPRITE
     #undef FL_DEBUG_ERROR_SCREENSHOT
     #undef FL_DEBUG_WARNING_SCREENSHOT
     #undef FL_DEBUG_DEVWARNING_SCREENSHOT
     #undef FL_DEBUG_CRITICALERROR_SCREENSHOT
     #undef FL_MODEL
     #define FL_TEXTURE_UNCACHED 0
     #define FL_TEXTURE_AUTOMIPMAP 0
     #define FL_TEXTURE_AUTOSWIZZLE 0
     #define FL_TEXTURE_ERRORTEX 0
     #define FL_TEXTURE_PRESERVENONALPHA 0
     #define FL_TEXTURE_PCX 0
     #define FL_TEXTURE_TGA 0
     #define FL_TEXTURE_BMP 0
     #define FL_TEXTURE_WAL 0
     #define FL_TEXTURE_PNG 0
     #define FL_TEXTURE_RAW 0
     #define FL_TEXTURE_MANIPULATION 0
     #define FL_SPRITE 0
     #define FL_DEBUG_ERROR_SCREENSHOT 0
     #define FL_DEBUG_WARNING_SCREENSHOT 0
     #define FL_DEBUG_DEVWARNING_SCREENSHOT 0
     #define FL_DEBUG_CRITICALERROR_SCREENSHOT 0
     #define FL_MODEL 0
#endif

#if FL_TEXTURE_AUTOMIPMAP < 0
     #undef FL_TEXTURE_AUTOMIPMAP
     #define FL_TEXTURE_AUTOMIPMAP 0
#else
#if FL_TEXTURE_AUTOMIPMAP > 7
     #undef FL_TEXTURE_AUTOMIPMAP
     #define FL_TEXTURE_AUTOMIPMAP 7
#endif
#endif

#if FL_TEXTURE_AUTOMIPMAP == 0
     #undef FL_TEXTURE_AUTOMIPMAP_PALETTED
     #define FL_TEXTURE_AUTOMIPMAP_PALETTED 0
#endif

#if FL_TEXTURE_ERRORTEX == 0
     #undef FL_TEXTURE_ERRORTEX_COMPILE
     #define FL_TEXTURE_ERRORTEX_COMPILE 0
#endif

#if FL_MODEL == 0
     #undef FL_MODEL_OBJ
     #undef FL_MODEL_MD2
     #define FL_MODEL_OBJ 0
     #define FL_MODEL_MD2 0
#endif

#if FL_FONT == 0
     #undef FL_NOTIFY_TRAYSIZE
     #define FL_NOTIFY_TRAYSIZE 0
#endif

#if FL_NOTIFY == 0
     #undef FL_NOTIFY_VOLUME
     #undef FL_NOTIFY_BATTERY
     #undef FL_NOTIFY_TIME
     #undef FL_NOTIFY_TRAYSIZE
     #define FL_NOTIFY_VOLUME 0
     #define FL_NOTIFY_BATTERY 0
     #define FL_NOTIFY_TIME 0
     #define FL_NOTIFY_TRAYSIZE 0
#endif

#if FL_NOTIFY_TRAYSIZE < 0
     #undef FL_NOTIFY_TRAYSIZE
     #define FL_NOTIFY_TRAYSIZE 0
#endif

#if FL_NOTIFY_TRAYSIZE == 0
     #undef FL_DEBUG_STATUS_NOTIFY
     #undef FL_DEBUG_ERROR_NOTIFY
     #undef FL_DEBUG_WARNING_NOTIFY
     #undef FL_DEBUG_DEVWARNING_NOTIFY
     #define FL_DEBUG_STATUS_NOTIFY 0
     #define FL_DEBUG_ERROR_NOTIFY 0
     #define FL_DEBUG_WARNING_NOTIFY 0
     #define FL_DEBUG_DEVWARNING_NOTIFY 0
#endif

/*#if FL_GRAPHICS_SIMPLE == 0
     #undef FL_GRAPHICS_SIMPLE_CLIPPING
     #undef FL_GRAPHICS_SIMPLE_IMAGESTACK
     #undef FL_GRAPHICS_SIMPLE_SPRITE
     #undef FL_GRAPHICS_SIMPLE_FONT
     #define FL_GRAPHICS_SIMPLE_CLIPPING 0
     #define FL_GRAPHICS_SIMPLE_IMAGESTACK 0
     #define FL_GRAPHICS_SIMPLE_SPRITE 0
     #define FL_GRAPHICS_SIMPLE_FONT 0
#endif*/
